# -*- coding: utf-8 -*-
"""MatrizesEmPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtHczGwWbvqoOHLagTqpGhtEdTz7M0os
"""

import numpy as np
# Exemplo de matriz quadrada de ordem 2
A=np.random.rand(2,2)
print('Matriz A: ',A)
#Exemplo de matriz de dimensáo qualquer
B = np.random.rand(3,4)
print('Matriz B: ', B)

#Matriz identidade
I = np.identity(3)
print(I)

#Matriz Transposta
A=np.random.rand(3,2)
A_transpose = np.transpose(A)
print (A)
print (A_transpose)

import numpy as np

A = np.array()

A = np.array([[1,-3,5],[8,0,3]])
B = np.array([[2,4],[6,10],[1,5]])

 #Multiplicação de matrizes
multm = np.matmul(A,B)
print('A multiplicação entre as matrizes é:',multm)

#Determinante
A=np.array([[1,9,5],[3,7,8],[10,4,2]])
detA = np.linalg.det(A)
print('O determinante da matriz é: ', detA)

import math as mt

A = ([[2,5,-3],[1,4,7],[-2,0,6]])
B = ([[mt.sqrt(2),2,1],[-1,mt.sqrt(3),3],[3,2,mt.sqrt(6)]])

detA = np.linalg.det(A)
detB = np.linalg.det(B)

print('Determinante da matriz A: ',detA)
print('Determinante da matriz B: ',detB)

""","""