# -*- coding: utf-8 -*-
"""Operações_em_Vetores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4QvQ2jKez5iKu54t0OHCw7JlvnlILeb
"""

import numpy as np

vetor = np.array([1,2,3,4,5,6,7,8])
print (vetor)

modulo = np.linalg.norm(vetor)
print(modulo)

"""Determine o módulo do vetor u = (-55,12) utilizando a linguagem python"""

u=([-55,12])
modulo_u = np.linalg.norm(u)
print(modulo_u)

"""Determine o módulo do vetor v = (11,-23,4) utilizando a linguagem python


"""

v=([11,-23,-4])
modulo_v = np.linalg.norm(v)
print(modulo_v)

u = np.array([-3,-5])
v = np.array([6,27])
#Soma
soma = u+v
print(f"A soma dos vetores é: {soma}")
#Subtração
subt = u-v
print(f"A subtração dos vetores é: {subt}")

#Multiplicação
multp = 9*u
print(f"A multiplicação: {multp}")
#Multiplicação por uma fração
multfra = (1/3)*v
print(f"A multiplicação por fração é: {multp}")

u = np.array([2,(5/3)])
v = np.array([-1,7])
#Soma
soma = u+v
#Subtração
sub = u-v
#Multiplicação
mult = u*3
#Multiplicação por fração
multfra= v*(1/5)
print(f"A soma dos vetores é:{soma} ")
print(f"A subtração dos vetores é:{sub} ")
print(f"A multiplicação é: {mult}")
print(f"A multiplicação por um vetor é: {multfra}")

import math as mt
angrad = (135*(np.pi/180))

a = np.array([-2,3])
b = np.array([7,4])
moda = np.linalg.norm(a)
modb = np.linalg.norm(b)

mod =mt.sqrt(moda**2+ modb**2 + (2*moda*modb*mt.cos(angrad)))
print(mod)

a = np.array([5,4,2])
b = np.array([1,3,-12])

print(np.dot(a,b))